### ISSUE TITLE
rls was renamed to rls-preview

### ISSUE THREAD

**Issue by cbordeman** [fungos/fungos.github.io#2]
On the page:
https://fungos.github.io/blog/2017/08/12/setting-up-a-rust-environment-on-windows/

Please update your rust installation tutorial accordingly as the suggested rustup command results in an error similar to:

error: toolchain 'nightly-x86_64-pc-windows-msvc' does not contain component 'rls' for target 'x86_64-pc-windows-msvc'

**Comment by fungos** [comment]
Thanks for the reminder, the post is up-to-date!
